# Generated by Django 2.2.4 on 2019-11-24 05:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmentld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_name', models.CharField(max_length=64, verbose_name='部门')),
                ('de_createTime', models.TimeField(auto_now_add=True, verbose_name='登记时间')),
                ('de_bz', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='em_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_name', models.CharField(max_length=64, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='em_nation_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na_name', models.CharField(max_length=64, verbose_name='民族')),
            ],
        ),
        migrations.CreateModel(
            name='em_province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na_name', models.CharField(max_length=64, verbose_name='省份')),
            ],
        ),
        migrations.CreateModel(
            name='tb_conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man', models.CharField(max_length=64, verbose_name='主持人')),
                ('title', models.CharField(max_length=64, verbose_name='会议主题')),
                ('content', models.TextField(verbose_name='主要内容')),
                ('time', models.TimeField(verbose_name='会议时间')),
                ('address', models.CharField(max_length=64, verbose_name='会议地点')),
                ('join', models.CharField(max_length=64, verbose_name='参与人员')),
                ('bz', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='tb_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('em_age', models.PositiveSmallIntegerField(verbose_name='年龄')),
                ('em_sex', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('em_IDCard', models.PositiveSmallIntegerField(verbose_name='身份证号')),
                ('em_born', models.CharField(max_length=32, verbose_name='出生日期')),
                ('em_marriage', models.SmallIntegerField(choices=[(1, '已婚'), (2, '未婚')], verbose_name='婚姻状况')),
                ('em_visage', models.SmallIntegerField(choices=[(1, '中共党员'), (2, '共青团员'), (3, '无')], verbose_name='政治面貌')),
                ('em_tel', models.PositiveSmallIntegerField(verbose_name='电话')),
                ('em_address', models.CharField(max_length=64, verbose_name='联系地址')),
                ('em_afterSchool', models.CharField(max_length=64, verbose_name='毕业学校')),
                ('em_speciality', models.CharField(max_length=64, verbose_name='所学专业')),
                ('em_culture', models.CharField(max_length=64, verbose_name='学历')),
                ('em_startime', models.TimeField(verbose_name='上岗时间')),
                ('em_creatime', models.TimeField(auto_now_add=True, verbose_name='登记时间')),
                ('em_bz', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('em_ancestralHone', models.ForeignKey(on_delete=models.Model, to='Backstage.em_city', verbose_name='籍贯')),
            ],
        ),
        migrations.CreateModel(
            name='tb_invitejob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(verbose_name='年龄')),
                ('born', models.CharField(max_length=32, verbose_name='出生日期')),
                ('job', models.CharField(max_length=64, verbose_name='应聘岗位')),
                ('specialty', models.CharField(max_length=64, verbose_name='所学专业')),
                ('culture', models.SmallIntegerField(choices=[(1, '博士'), (2, '硕士'), (3, '本科'), (4, '大专'), (5, '其他')], verbose_name='学历')),
                ('afterSchool', models.CharField(max_length=64, verbose_name='毕业学校')),
                ('tel', models.PositiveSmallIntegerField(verbose_name='电话')),
                ('address', models.CharField(max_length=64, verbose_name='联系地址')),
                ('createTime', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bz', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='tb_pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_month', models.TimeField(verbose_name='当前月份')),
                ('pay_baseMoney', models.PositiveSmallIntegerField(verbose_name='基本工资')),
                ('pay_overtime', models.PositiveSmallIntegerField(default=0, verbose_name='加班工资')),
                ('pay_age', models.PositiveSmallIntegerField(default=0, verbose_name='工龄费')),
                ('pay_check', models.PositiveSmallIntegerField(default=50, verbose_name='考勤费')),
                ('pay_absent', models.PositiveSmallIntegerField(default=0, verbose_name='旷工费')),
                ('pay_safety', models.PositiveSmallIntegerField(default=100, verbose_name='保险费')),
                ('pay_emId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backstage.tb_employee', verbose_name='员工号')),
            ],
        ),
        migrations.AddField(
            model_name='tb_employee',
            name='em_createName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backstage.user', verbose_name='登记人名'),
        ),
        migrations.AddField(
            model_name='tb_employee',
            name='em_departmentld',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='Backstage.departmentld', verbose_name='部门名称'),
        ),
        migrations.AddField(
            model_name='tb_employee',
            name='em_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backstage.em_nation_choice', verbose_name='民族'),
        ),
        migrations.CreateModel(
            name='tb_cj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='主题')),
                ('type', models.SmallIntegerField(choices=[(1, '奖励'), (2, '惩罚')])),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
                ('money', models.PositiveSmallIntegerField(verbose_name='金额')),
                ('time', models.TimeField(verbose_name='惩奖时间')),
                ('em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backstage.tb_employee', verbose_name='员工号')),
            ],
        ),
        migrations.AddField(
            model_name='em_city',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backstage.em_province', verbose_name='隶属省份'),
        ),
    ]
