# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_info',
        ),
        migrations.AlterUniqueTogether(
            name='favor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='favor',
            name='news',
        ),
        migrations.RemoveField(
            model_name='favor',
            name='user_info',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_type',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Favor',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
    ]
